#!/bin/bash
#Glanel Houenouvi
#Week2 Command
echo "print the sentence "Hello Amigo How are You"
echo "Hello Amigo How are you"
sleep 1
echo "create a file FA"
touch FA
sleep 1
echo "put word Papy in file FA"
echo "Papy" > FA
sleep 1
echo "Globbing everything within directory"
echo *
echo "print the actual directory"
pwd
sleep 1
echo "run the output of file FA"
ls -l FA

echo "end of script"
