#!/bin/bash
#Glanel Houenouvi
#Week 3 Command
#Week 3 Command
echo "send this sentence to Trash (dev/null)"
echo "Chers amis au revoir" > /dev/null
echo "show all the device in the system"
blkid
sleep 1
echo "find the system file"
find /sys | grep sd | less
echo "Show the process partition"
ls /proc/partitions
sleep 1
echo "end of script"
